version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.ru
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - db
